import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

<<<<<<< HEAD
export default function RootLayout({
=======
export default async function RootLayout({
>>>>>>> 13da7eec36cd1ed95eddef964b4edcb98fe01b7d
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="antialiased text-gray-800 dark:bg-black dark:text-gray-400">
          <div className="container px-8 mx-auto xl:px-5  max-w-screen-lg py-5 lg:py-8">
            <nav className="my-4">
              <div className="flex flex-wrap justify-between md:gap-10 lg:flex-nowrap">
                <div className="flex items-center justify-between w-full lg:w-auto">
                  <button
                    aria-label="Toggle Menu"
                    className="px-2 py-1 ml-auto text-gray-500 rounded-md lg:hidden focus:text-blue-500 focus:outline-none dark:text-gray-300 "
                    id="headlessui-disclosure-button-:r7:"
                    type="button"
                    aria-expanded="false"
                  >
                    <svg
                      className="w-6 h-6 fill-current"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"
                      ></path>
                    </svg>
                  </button>
                </div>
                <div className="flex items-center gap-3">
                  <div className="flex-col items-center hidden w-full lg:flex lg:flex-row lg:w-auto ">
                    <div className="relative text-left">
                      <button
                        className="flex items-center gap-x-1 transition-all py-2 px-5  font-medium outline-none focus-visible:text-blue-500 focus-visible:ring-2 rounded-full ring-blue-100  text-gray-600 dark:text-gray-400  inline-block px-4 py-2"
                        id="headlessui-menu-button-:r9:"
                        type="button"
                        aria-haspopup="true"
                        aria-expanded="false"
                      >
                        <span>Home</span>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                          aria-hidden="true"
                          className="w-4 h-4 mt-0.5"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd"
                          ></path>
                        </svg>
                      </button>
                    </div>
                    <a
                      className=" py-2 px-5 font-medium text-gray-600 dark:text-gray-400 hover:text-blue-500 outline-none focus-visible:text-blue-500 focus-visible:ring-2 rounded-full ring-blue-100"
                      target=""
                      rel=""
                      href="/about"
                    >
                      About
                    </a>
                    <a
                      className=" py-2 px-5 font-medium text-gray-600 dark:text-gray-400 hover:text-blue-500 outline-none focus-visible:text-blue-500 focus-visible:ring-2 rounded-full ring-blue-100"
                      target=""
                      rel=""
                      href="/contact"
                    >
                      Contact
                    </a>
                    <div className="relative text-left">
                      <button
                        className="flex items-center gap-x-1 transition-all py-2 px-5  font-medium outline-none focus-visible:text-blue-500 focus-visible:ring-2 rounded-full ring-blue-100  text-gray-600 dark:text-gray-400  inline-block px-4 py-2"
                        id="headlessui-menu-button-:ra:"
                        type="button"
                        aria-haspopup="true"
                        aria-expanded="false"
                      >
                        <span>Pages</span>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                          aria-hidden="true"
                          className="w-4 h-4 mt-0.5"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd"
                          ></path>
                        </svg>
                      </button>
                    </div>
                    <a
                      className=" py-2 px-5 font-medium text-gray-600 dark:text-gray-400 hover:text-blue-500 outline-none focus-visible:text-blue-500 focus-visible:ring-2 rounded-full ring-blue-100"
                      target="_blank"
                      rel="noopener"
                      href="https://web3templates.com/templates/stablo-minimal-blog-website-template"
                    >
                      Purchase
                    </a>
                  </div>
                  <div className="hidden lg:block">
                    <form action="/search" method="GET">
                      <div className="relative">
                        <input
                          type="text"
                          placeholder="Search Blog"
                          name="q"
                          id="q"
                          className="w-full px-3 py-2 border rounded-md outline-none focus:border-gray-300 focus:shadow-sm dark:bg-gray-900 dark:border-gray-600 dark:focus:border-white"
                          value=""
                        />
                        <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="2"
                            stroke="currentColor"
                            aria-hidden="true"
                            className="w-4 h-4 text-gray-400"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                            ></path>
                          </svg>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </nav>
          </div>

          {children}
        </div>
      </body>
    </html>
  )
}
