import 'swiper/css'
import 'swiper/css/free-mode'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import Footer from './Components/Footer'
import Header from './Components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="antialiased text-gray-800 ">
          <Header />
          <div className="pt-12">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
